version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-gameflow
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - gameflow-network

  gameflow-api:
    build:
      context: ./
      dockerfile: /Dockerfile # Caminho correto para o Dockerfile
    container_name: gameflow-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GameFlowDB;User Id=sa;Password=YourPassword123;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - gameflow-network

networks:
  gameflow-network:
    driver: bridge

volumes:
  sqlserver_data:
